services:
  frontend:
    image: rubenag83/movi-info-react-dotnet-frontend
    build: 
      context: ./front-react
      platforms:
        - "linux/amd64"
      args:
        - VITE_DOT_NET_BACK=/api/
      no_cache: true
    ports:
      - "8080:80"
    networks: 
      - frontend
      - backend
    restart: unless-stopped
  
  backend:
    image: rubenag83/movi-info-react-dotnet-backend
    build:
      context: ./back-dotnet/MoviInfoBack
      platforms:
        - "linux/amd64"
    networks: 
      - backend
    restart: unless-stopped

networks: 
  frontend:
  backend: