# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
services:
  backend:
    image: rubenag83/movi-info-react-dotnet-backend:amd64
    build:
      context: .
      platforms:
        - "linux/amd64"
